### ISSUE TITLE
HTTPS is redirected to HTTP

### ISSUE THREAD

**Issue by pheyvaer** [LinkedDataFragments/Client.js#34]
When doing a query to an LDF server with https, the fragments are requested via http instead of https.
When the client is created, a request with https is done (as shown in the console), but once fragments are requested http is used. Chrome and Firefox complain about this if the initial page that is using the LDF client is being served using https with the error about 'mixed content'.

**Comment by rubensworks** [comment]
From where are you querying?

Browsers can complain if you are doing requests from a http webpage to a https webpage, so you may want to use a https-enabled webclient like this one: https://query.linkedsoftwaredependencies.org/

Command-line should work fine in any case.

**Comment by pheyvaer** [comment]
I'm querying from a Webpage that is being served via https, but I say to the client to query the server with https, so why does it happen via http then?

Which version of the ldf-client are using at LSD then?

Yes, command line indeed works.

**Comment by rubensworks** [comment]
Then that won't be the problem...

One other possible cause might the an incorrectly configured baseURL. Does it contain https?
You can check this by manually checking the next page url's when doing a `curl -H 'Accept: text/turtle'` request.
(Also, if you ever tested it on the non-https endpoint, make sure to properly clean your cache)

LSD is using the jQuery Widget of this version: https://github.com/LinkedDataFragments/jQuery-Widget.js/commit/c64c54de18a277f874c22d7b163fc8216d64fca8

**Comment by pheyvaer** [comment]
OK, that narrows down the problem to the server, instead of the client I think.
The config of the server has https in the baseurl, but the next page url's use http.

**Comment by rubensworks** [comment]
Can you show me your config file.

**Comment by rubensworks** [comment]
For reference: adding `"protocol": "http"` didn't solve the issue.

@RubenVerborgh Any idea on what else could cause this?

**Comment by mielvds** [comment]
Weird, never had this issue. Can't be the client idd, because it just follows links. Is there a redirect involved? Could also be NGINX messing things up...

**Comment by pheyvaer** [comment]
Nginx redirects http to https, but that would not explains why the RDF returned by the LDF server has links without https, right?

**Comment by rubensworks** [comment]
Perhaps NGINX is not forwarding all required information.
@pheyvaer Could you try adding these lines to your `location` block inside your NGINX site config?

```
proxy_set_header Host $http_host;
proxy_pass_header Server;
```

**Comment by pheyvaer** [comment]
That information is already there.

**Comment by rubensworks** [comment]
Ok, then I'm out of ideas again for the moment :/

**Comment by mielvds** [comment]
it does right? NGINX translates the protocol, but the server doesn't know that, so it keeps creating http links?

**Comment by mielvds** [comment]
What does NGINX do exactly? Input: HTTPS, Output HTTP?

**Comment by pheyvaer** [comment]
```
location / {
        proxy_pass http://127.0.0.1:3000$request_uri;
	proxy_set_header Host $http_host;
	proxy_pass_header Server;
}

if ($scheme != "https") {
        return 301 https://$host$request_uri;
}
```

So the requests are send to the ldf server running on port 3000 and if http is used, go for https.
I tried setting the `proxy_pass` to https, but that doesn't work, because I don't have ssl set up on the ldf server (should that also happen there?).

**Comment by rubensworks** [comment]
That looks ok.
On the LDF server you don't have to setup SSL, only make sure your baseURL includes https and `"protocol": "http"` is present.

**Comment by mielvds** [comment]
I think we bumped on an edge case here. The HTTPS support in the LDF Server does not take HTTPS proxies into account.

Two solutions would be:
- Let NGINX rewrite the controls in the response to HTTPS (not really a solution, inefficient)
- add a proxy setting to the server which only does the URL construction, but not activate the SSL layer (because NGINX does that)

**Comment by rubensworks** [comment]
This edge case should've been fixed in https://github.com/LinkedDataFragments/Server.js/commit/7fbdae8ed7b34721e0240cbbb8a60d228144037a I think.

We do exactly the same thing as @pheyvaer on http://data.linkeddatafragments.org/ and https://fragments.linkedsoftwaredependencies.org/

**Comment by mielvds** [comment]
Not exactly. The problem is this:

https://github.com/LinkedDataFragments/Server.js/blob/master/lib/LinkedDataFragmentsServer.js#L17

and 

https://github.com/LinkedDataFragments/Server.js/blob/master/lib/controllers/TriplePatternFragmentsController.js#L68

So this is the scenario that occurs

- Client requests `https://x/fragment`
- NGINX turns it into `http://x/fragment`
- LDF server receives `http://x/fragment` as requestUrl
- LDF server constructs controls from the requestUrl: `http://y/fragment`
- NGINX proxies body with `http://y/fragment` inside, but under `https`

 

Then, why should the protocol be `http` and not `https`?

**Comment by pheyvaer** [comment]
OK, so the problem with the https in the results of the LDF server seems to be fixed. I used `baseUrl` instead of `baseURL`, so the URL was not read at all... 😫 Maybe we could add some information to the output when the server is started that states which baseURL, if any, is used?

I'm gonna have a look at the client specific code to see if any issues are still present there, and I'll report back.

**Comment by mielvds** [comment]
I guess we should include that in https://github.com/LinkedDataFragments/Server.js/blob/master/bin/ldf-server#L180
 
Also, it's correctly in the documentation :)

Anyways, for what the client is concerned, this issue is closed.

**Comment by rubensworks** [comment]
I'll include this in the `feature-lsd` branch, as I'm making changes related to that anyways.
